# Generated by Django 3.0.2 on 2020-02-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='Name',
            new_name='name',
        ),
    ]
