# Generated by Django 3.0.2 on 2020-02-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0002_auto_20200204_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Dog',
        ),
    ]
