# Generated by Django 3.0.2 on 2020-03-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
