# Generated by Django 3.0.2 on 2020-03-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0005_auto_20200328_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
