# Generated by Django 3.0.2 on 2020-03-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('ratingFor', models.IntegerField()),
                ('ratingBy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
