# Generated by Django 3.0.2 on 2020-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0008_auto_20200328_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('rideId', models.IntegerField()),
                ('userRole', models.IntegerField()),
            ],
        ),
    ]
