# Generated by Django 3.0.2 on 2020-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0009_user_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
