# Generated by Django 3.0.2 on 2020-03-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0010_userdata_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
