# Generated by Django 3.0.2 on 2020-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0011_delete_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingByUserId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ratingForUserId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='endZip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startZip',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicleMake',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicleModel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicleYear',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user_ride',
            name='rideId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_ride',
            name='userId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_ride',
            name='userRole',
            field=models.IntegerField(null=True),
        ),
    ]
