# Generated by Django 3.0.2 on 2020-04-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitchhikeapp', '0012_auto_20200329_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userName',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
